### ISSUE TITLE
Support for new test options

### ISSUE THREAD

**Issue by arlake228** [perfsonar/meshconfig-admin#11]
We've added a few new options for the various tools in the mesh-config to make things feature complete with pScheduler in 4.0. The new options are as follows:

Throughput tests:
- **tcp_bandwidth** - Int, just like udp_bandwidth except used when protocol is TCP. 
- **mss** - Int, TCP maximum segment size in bytes. only valid when protocol is TCP
- **dscp** - Int, the dscp bits to set in IP header
- **dynamic_window_size** - Int, TCP window size in bytes. only valid when protocol is TCP
- **no_delay** - set TCP no delay, disabling Nagle's Algorithm. only valid when protocol is TCP
- **congestion** - only valid when protocol is TCP. only valid when protocol is TCP
- **flow_label** -  Int, set the IPv6 flow label
-  **server_cpu_affinity** - Int which is the ID of the CPU socket to use on the server
- **client_cpu_affinity**- Int which is the ID of the CPU socket to use on the client

OWAMP tests:
- **output_raw** - boolean, include raw output in reported results

Ping tests:
- **flowlabel** - Int, set the IPv6 flow label
- **hostnames** - Boolean, include DNS names in result
- **suppress_loopback** - Boolean,  Suppress loopback of multicast packets.
- **deadline** - Int, the number of seconds to wait for the entire test to complete
- **timeout** - Int, the number of seconds to wait for a ping packet

Traceroute 
- **algorithm** - only valid when tool is paris-traceroute. the algorithm to use.
- **as** - Boolean, True means to include the AS number in results
- **fragment** - Boolean, allow IP fragmentation
- **hostnames** - Boolean, include DNS names in result
- **probe_type** - One of "icmp", "udp", "tcp". Protocol to use for traceroute
- **queries** - Int, the number probe packets to send for a given TTL
- **sendwait** - Int, the number of seconds to wait for a probe packet
- **wait** - Int, the number of seconds between probes

**Comment by soichih** [comment]
@arlake228 It looks like most (if not all?) of these are not yet published to http://docs.perfsonar.net/config_mesh.html My questions are..

1) Should I go ahead and add these? - assuming that production version of MCA won't be taking over the old version any time soon.
2) If we start publishing with these new config, what happen if older version of meshconfig agent tries to read it? Do I need to add a capability to show different set of parameters based on some URL query? (like ?version=3.5), or does the old version simply ignore parameter that aren't supported?
3) For "int" fields, do you actually mean an integer (not decimal)? Also, is there min/max for each integers?

**Comment by arlake228** [comment]
On January 24, 2017 at 6:21:43 AM, Soichi Hayashi (notifications@github.com)
wrote:

@arlake228 <https://github.com/arlake228> It looks like most (if not all?)
of these are not yet published to http://docs.perfsonar.net/config_mesh.html
 My questions are..

   1. Should I go ahead and add these? - assuming that production version
   of MCA won't be taking over the old version any time soon.

See http://docs.perfsonar.net/release_candidates/4.0rc2/config_mesh.html.
These options are not in the released version yet, they are new in 4.0.
Your GUI should be targeting 4.0. Also, since I posted this the ping
“flowlabel” option has changed to flow_label.


   1.
   If we start publishing with these new config, what happen if older
   version of meshconfig agent tries to read it? Do I need to add a capability
   to show different set of parameters based on some URL query? (like
   ?version=3.5), or does the old version simply ignore parameter that aren't
   supported?

It will fail if any of the new options are used. I think probably the
correct thing to do is have a way to label the minimum supported version of
the various options in the GUI but let people set them. You don’t want to
present a different set of options to the older hosts, since that could
lead to misleading results. In an ideal world you would maybe check the
version of the hosts in the mesh when you set the test parameters and throw
a warning if any of the hosts are below the minimum version. You could get
that from the “bundle-version” field of the LS host record.



   1.
   For "int" fields, do you actually mean an integer (not decimal)? Also,
   is there min/max for each integers?

Correct, int = integer. The min on all of them is 0. No strict maximums.



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/soichih/meshconfig-admin/issues/11#issuecomment-274815118>,
or mute the thread

**Comment by soichih** [comment]
So.. this sounds very iffy.

Basically, when I publish the meshconfig, I need to 
1) Find out who is downloading the meshconfig.
2) Lookup the hostname stored in the MCA's host list and see if we know about this host.
3) If we know, then lookup `pshost-bundle-version`. If it's >4, add those new parameters, if not, don't.

For 1), I think some hosts doesn't allow reverse lookup - so we will not find the proper hostname - or get the wrong hostname.
For 2), If someone is running gnerate_meshconfig on a different host from where the toolkit is actually running (I am not sure if such setup exists out there, but this was the case for me when I was testing toolkit using Docker), then I won't have that hostname listed in MCA host list.
For 3) A lot of hosts are currently not publishing to the LS. We have either *simualted hosts*; ones that gocdb2sls service is guessing its content (no "pshost-bundle-version*), or *adhoc* hosts, ones that entered manually by the admin ("pshost-bundle-version"might not exist, or entered in correctly). 

I think there are too many issues to reliably guess that the toolkit is >v4 or not. We could of course, assume that all hosts are v3 until proven otherwise.. but overall, I just don't like the fact that we publish different content based on who is accessing it (I think it's super confusing for user's point of view).

Can the meshconfig agent itself updated to ignore unknown test parameters?

**Comment by arlake228** [comment]
If we could update the meshconfig at will everywhere then we wouldn't have this issue :)  We do run auto-updates which usually covers about 75-80% of known hosts, but that remaining % is the problem. I think what we should do is include the new parameters but label them as 4.0. If the admin thinks they will have hosts in the mesh running < 4.0 then its on them to not use them.

**Comment by soichih** [comment]
@arlake228 

I am working on adding those new parameters to the testspec UI, and I've noticed a couple of potential issues.

I am reading this doc
> http://docs.perfsonar.net/release_candidates/4.0rc2/config_mesh.html#dscp-directive

Throughput Test
`tool` doesn't have nuttcp listed as possible value, but I think this was added for 4.0?
`dynamic_window_size` is not listed under the doc.
`congestion` field type is marked as `VALUE` but should this be a free form string, or use <select> with list from https://en.wikipedia.org/wiki/TCP_congestion_control and description for each algorithms?
`flow_label` This field has to be integer, correct? Is there a maximum?

Owamp Test
`tos_bits` wasn't listed on your list, but I've added it to MCA

Ping Test
flow_label says `where type is pinger and tool is ping6`. As far as I know, there is no option to specify tool for ping test. Is this added for v4? If so, can you list all possible tools?
`hostnames` says "test_spec where type is traceroute and tool is ping" You mean "type is pinger" correct?
`tos_bits` wasn't listed on your list, but I've added it 

Traceroute
`as` `fragment` `hostnames` `queries` `sendwait` `wait` Aren't these only for the traceroute tool (not for paris-traceroute or tacepath?) Or are these options somehow turned into appropriate command line options for other tools?
`probe_type` Isn't this only for paris-traceroute? 
`tos_bits` wasn't listed on your list, but I've added it.


To deal with v4 only options, I am thinking about adding an option in the UI for configured test to include v4 only option in generated meshconfig or not.

**Comment by soichih** [comment]
@arlake228 Can you comment on my previous update?

**Comment by arlake228** [comment]
Throughput Test

- nuttcp is indeed a valid tool now
- dynamic_window_size got dropped, so don't add it
- A drop down for congestion control would be cool. Maybe may it a combo box so someone could enter a custom value since the list can change. 
- flow_label is currently defined as a string, but after talking with the throughput tool developer upon seeing this, it should indeed be an int. We are changing it to be an int in the code. 

Owamp Test

- Cool, tos_bits is indeed supported so thanks for adding

Ping Test

- You are right, the documentation that references ping6 is incorrect. You can't add tool to a pinger test. I think the person that wrote that meant you can only use flow_label for IPv6 tests since flow_label goes in the IPv6 packet header. Fixing now.
- Yep, the hostnames stuff was just a typo. Should be fixed now.
- Thanks again for adding tos_bits

Traceroute Test

- Yes, the options you listed are specific to traceroute. If you don't specify a tool, but choose options specific to a subset of tools it will rule out the others from consideration. If you try to specify a tool and options it does not support, then you will get an error when you try to run the test.
- `probe-type` is supported by regular traceroute as well.
- ..and thanks again for adding tos_bits

**Comment by soichih** [comment]
Andy,

Thanks for the info. Most of it made sense, and I've updated as you've instructed. 

However, I still have questions on following.

Ping test

> You can't add tool to a pinger test.

Just to be clear.. you want me to remove the capability to specify "tool" for ping testspec altogether, and that also implies removing flow_label? I still see flow_label listed in your doc here (http://docs.perfsonar.net/release_candidates/4.0rc2/config_mesh.html#id12) Are you going to remove it?

Traceroute  Test

> Yes, the options you listed are specific to traceroute.

OK.  FYI.. the /4.0rc2 doc still shows these options listed as applied to all 3 traceroutes. `Contexts:	test_spec where type is traceroute` should be updated to `Contexts:	test_spec where type is traceroute and tool is traceroute`

>  If you don't specify a tool, but choose options specific to a subset of tools it will rule out the others from consideration

I couldn't quite make sense of this, but I think you are just describing an extra feature for the UI that I could implement?

Thanks!

**Comment by arlake228** [comment]
On February 27, 2017 at 3:44:49 PM, Soichi Hayashi (notifications@github.com)
wrote:

Andy,

Thanks for the info. Most of it made sense, and I've updated as you've
instructed.

However, I still have questions on following.

Ping test

You can't add tool to a pinger test.

Just to be clear.. you want me to remove the capability to specify "tool"
for ping testspec altogether, and that also implies removing flow_label? I
still see flow_label listed in your doc here (
http://docs.perfsonar.net/release_candidates/4.0rc2/config_mesh.html#id12)
Are you going to remove it?

No, flow_label stays. The only thing that was wrong was the text saying you
could specify a tool. You can’t specify a tool because there is no need to,
the underlying software with do the right thing with regards to IPv6.



Traceroute Test

Yes, the options you listed are specific to traceroute.

OK. FYI.. the /4.0rc2 doc still shows these options listed as applied to
all 3 traceroutes. Contexts: test_spec where type is traceroute should be
updated to Contexts: test_spec where type is traceroute and tool is
traceroute

If you don't specify a tool, but choose options specific to a subset of
tools it will rule out the others from consideration

I couldn't quite make sense of this, but I think you are just describing an
extra feature for the UI that I could implement?

The tool is not a required field. pScheduler is capable of making an
intelligent decision about which tool to use based on what’s installed on
the local system and the options each tool supports. For example, If you
specify an option that only paris-traceroute supports but do not explicitly
call out the tool, then pScheduler will be smart enough to know that only
paris-traceroute can support that option and choose that as the tool.




Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/soichih/meshconfig-admin/issues/11#issuecomment-282847234>,
or mute the thread

**Comment by soichih** [comment]
I've restored ping/flow_label option - and make it available regardless of ipv4/6 selection).

I think this is close to be done, but I need some extensive testing done (especially after v4 is released) by  experts of these new fields. Even with that, I am afraid there will be a lot of minor bugs that slipped through which will end up generating invalid sets of test parameters.. I believe we will need to patch things as we go along.

**Comment by apertome** [comment]
I believe all the 4.0 options have now been added. Closing this issue, but this work will continue in #30 (adding 4.1 options and adopting psConfig format).

**Comment by apertome** [comment]
It would be good to get some feedback from @arlake228 on what I've done here, in case I missed something or made a mistake.
