### ISSUE TITLE
Add "Host Description" field for host collection

### ISSUE THREAD

**Issue by soichih** [perfsonar/meshconfig-admin#25]
Currently "Sitename" is used to populate meshconfig's host description (which is used to show labels in the meshconfig agent). "Sitename" is often not set with a descriptive names, and we need a way to override this if necessary.

We should add "Host Description" field for host collection and allow administrator to edit it (similar to how toolkit_url is edited) and use this to override meshconfig description which is currently set by "Sitename". "Host Description" field will take precedence.

**Comment by ShawnMcKee** [comment]
Hi Soichi,

I think this is working well so far.  Have a look at the testbed mesh where I put in consistent entries for the Host Description in MCA:

http://maddash.aglt2.org/maddash-webui/index.cgi?dashboard=perfSONAR%20Testbed

I would like to watch this for a while to ensure nothing funny comes up but it looks like it is working as intended to me.

Shawn

**Comment by apertome** [comment]
It sounds to me like this is already fixed? @ShawnMcKee can you comment?

**Comment by ShawnMcKee** [comment]
Yes, I believe this one is already done.  Checking on host shows it is there in MCA.

BASIC INFORMATION

Site Name *
(OWAMP Measurement Point at atlas-swt2.org)
Comes from the lookup service (or guessed if it's not set)

Host Description
Host description used in meshconfig
Host description is used by maddash for host labels. If not set, Site Name will be used instead

The only issue may be that we haven't extensively tested the over-ride behavior to verify that strange entries don't break something.

Shawn

**Comment by apertome** [comment]
After testing this, it appears to me that the input is being properly escaped, and could not get anything I entered to break anything.

So, I think this is done.
