### ISSUE TITLE
MA endpoint http/https selection

### ISSUE THREAD

**Issue by soichih** [perfsonar/meshconfig-admin#28]
Currently, MCA assumes that all MA endpoints are served via http://. LS does not provide this information reliably so that MCA can use it. 

Shawn suggests that we should add capability within MCA to override the protocol in case there are toolkit instances out there that are https:// only. Marian mentions that his instance is one of such instance (?)

**Comment by apertome** [comment]
The simplest, most flexible way to do this is likely to just allow overriding the MA URL entirely, this will support weird use cases people may have.

**Comment by apertome** [comment]
This is now being handled as part of #5 .
