### ISSUE TITLE
Document ma_override functionality

### ISSUE THREAD

**Issue by soichih** [perfsonar/meshconfig-admin#3]
ma_override is currently undocumented.

**Comment by ShawnMcKee** [comment]
In general we will need some more documentation on the API and various hidden features that are enabled.

**Comment by soichih** [comment]
Shawn, 

Just for curiosity.. do you know who else uses ma_override other than the perfSONAR datastore instance? Is this used by other users / use-cases?

**Comment by ShawnMcKee** [comment]
Hi Soichi,

I believe it would be used for "lightweight" instances where you want to
send data for "bigger" sets of tests to another off-host MA.   (You don't
want to overload the local MA because it can't handle the additional load).

Our planned use-cases for controlling the MA include setups where we might
want some meshes to report to a central "mesh-specific" archive in addition
to report to the local MA.   Some groups may want to have regional  or
national collectors that should get a copy of all tests.

It is problematic?  Thanks,

Shawn

**Comment by soichih** [comment]
Thanks for the info.

I was asking this because, if it's more than a single occurrence issue, we should somehow take advantage of existing meshconfig feature to set MA at the root level of the meshconfig. MA can be specified at different levels (https://github.com/soichih/meshconfig-admin/issues/5#issuecomment-274826248) 

BUT.. the way meshconfig currently works is that, the MA configuration at root level does not *override* the site/host level MA configuration.. It's actually the other way around. root level MAs are overridden by host MA (if specified).

MCA currently allows MA override at host level, but not root / test / site level.

So, here is what I think we could do ..
1) We allow config, and test level MA *override* on MCA UI.
2) If config level MA override is specified, we suppress generating MA at lower levels - so that config level MA basically *acts* as  an override.

By doing this, we implement ma_override feature in much more meshconfig friendly way. We can also allow other users to override MAs at various levels. 

Problem with this is approach is that.. it could be very confusing to the administrator; because we are changing the way MA configuration is interpreted.. I think proper in-UI help text could help user to understand what it does.. however. 

I will Andy about this also.

**Comment by apertome** [comment]
There are some possible future directions here, but this request is really just to document the current functionality.

**Comment by apertome** [comment]
The way MAs are handled has changed quite a bit now; the default is now NOT to log to archives on each endpoint, but this can be overridden at the "config" level.

You can also add additional MAs for each config and host now. This should cover all the functionality requested here.
