### ISSUE TITLE
Problems with '/' character in Mesh Names (JSON output)

### ISSUE THREAD

**Issue by ShawnMcKee** [perfsonar/meshconfig-admin#31]
If we enter information in the mesh config in both the Name and Description fields the resulting JSON that gets published has a description in the published JSON that  concatenates the those 2 fields int the 'description'.   For example on  MCA we have "Name:   Belle II Mesh Config"  and "Description: Test" and the  published  JSON output looks like:

description: "Belle II Mesh Config / Test",

The presence of the '/' causes MaDDash to fail to process the mesh and results in errors like:

ERROR 2017-06-13 06:59:01,536 Error handling request: null

This show up in the maddash-server.log file.    Can we find another way to concatenate these fields?
Should the be concatenated or should the two source areas go to different locations in the JSON?

Shawn

**Comment by soichih** [comment]
We could use - (dash) instead?

Also, I believe user can enter "/" as a config name, or the description. If MadDash can't handle /, then we should prevent user from entering those characters as part of config name, or the description.

**Comment by ShawnMcKee** [comment]
What about using a ':' or will that  cause a URL issue?  I was thinking of:
<Name>: <Description>

Shawn

**Comment by apertome** [comment]
I've changed the separator for the name/description to name: description. I have not yet disallowed input of / in the name and description fields.

**Comment by apertome** [comment]
I've changed the frontend and backend to prevent `/` characters in mesh `name` values, but not yet changed `description` in the same way

**Comment by apertome** [comment]
Description has been updated accordingly. This is done.
