### ISSUE TITLE
Allow multiple MA endpoints per host

### ISSUE THREAD

**Issue by soichih** [perfsonar/meshconfig-admin#5]
Current version(?) of meshconfig allows multiple MA endpoints per host. I should expose this capability by allowing users to select multiple MAs via MCA.

**Comment by ShawnMcKee** [comment]
I have also queried Andy Lake to see what other updates/changes have occurred to the mesh-config that may also need to be enabled in the GUI.

**Comment by soichih** [comment]
I met with @arlake228 I last year and I believe we agreed that - even though we can list as many MAs as we want, we should actually list one MA per service... Andy, can you correct me if I am wrong?

```
measurement_archives: - [
- {
read_url: "https://192.41.236.35/esmond/perfsonar/archive",
write_url: "https://192.41.236.35/esmond/perfsonar/archive",
type: "perfsonarbuoy/ping"
},
- {
read_url: "https://192.41.236.35/esmond/perfsonar/archive",
write_url: "https://192.41.236.35/esmond/perfsonar/archive",
type: "perfsonarbuoy/owamp"
},
- {
read_url: "https://192.41.236.35/esmond/perfsonar/archive",
write_url: "https://192.41.236.35/esmond/perfsonar/archive",
type: "perfsonarbuoy/pscheduler"
},
- {
read_url: "https://192.41.236.35/esmond/perfsonar/archive",
write_url: "https://192.41.236.35/esmond/perfsonar/archive",
type: "perfsonarbuoy/traceroute"
}
],
```

**Comment by ShawnMcKee** [comment]
I believe the use-case for more that one MA is when you want to send your
information to more than one place. I can imagine this would be useful when
you want to keep a "central" MA but also have the local MA on each host
keep the data.

Shawn

**Comment by arlake228** [comment]
The way MAs are structured currently you have to define them per service, but you can define them per service at one or both of the host and test level. For example, I may define a set of measurement archives at the host level meaning I want everything run on that host to go to that set of archives. I may also define things at the test level meaning I want all my results from participating in that test to go to the defined MA, but I don't want other tests run on my host to go to that MA. As shawn said, there is definitely a use case for things like "I want all my tests to be stored in my local MA, but I want my PuNDIT tests to also be sent to a central MA".

That being said one of my last open 4.0 issues at perfsonar/mesh-config#25 is to make sure all that works like it should, but shouldn't change how you define it in the file.

**Comment by soichih** [comment]
@arlake228 Thanks for the info. Looks like I need to rethink the way I am currently allowing user to override MAs. 

Currently, I am relying on the MCA super-admin to set host/service level MA override. MCA doesn't have good mechanism to map MCA user and the toolkit host administrator (since most toolkit admin won't be registering to MCA). I do, however, have clearly defined set of admins for the config/test in MCA. So, I think it makes sense if I stop using the host level MA override and instead define them at the test level.. But this means we won't be able to set *default* MA for each host (most likely to send to the local MA).

I am not sure how to solve this..

**Comment by soichih** [comment]
Andy, I've made this suggestion about allowing user to configure MA as various levels..
> https://github.com/soichih/meshconfig-admin/issues/3#issuecomment-276211851

It's not really about allowing multiple MAs for each host, but I wonder if you could chime in.

**Comment by apertome** [comment]
I discussed this with Soichi recently and it sounds like there is fairly significant work needed to make this happen. The GUI assumes only one MA in its datastructures, UIs, webservices etc; this needs to be adapted

**Comment by apertome** [comment]
I discussed this further with Andy today and currently the plan is this:

- [ ] Remove the per-service MA override for each host
- [ ] Add a place in the test config to configure the MA(s) for each test
- [ ] Add a place in the host config to specify whether to send results to the local MA
- [ ] Add a place in the host config to specify additional MAs to send to

This deviates enough from the existing structure that the whole MA functionality needs to change, so we might as well support multiple MAs from the start.

**Comment by arlake228** [comment]
Should we split this into multiple issues and make this an epic? 13 points seems like it will exceed one sprint.

**Comment by apertome** [comment]
Revised the estimate down a bit, as this looks a little less involved than I initially thought.

I think this is doable in ~2 weeks, but not having done anything on it yet, probably won't get done this sprint.

I can break it up into smaller tasks if that will make tracking it easier. Thoughts?

**Comment by apertome** [comment]
We also need ability to override the local host MA URL. (from #28)

`Currently, MCA assumes that all MA endpoints are served via http://. LS does not provide this information reliably so that MCA can use it.`

**Comment by apertome** [comment]
This is done or close to it, reviewing some stuff.
